### PR TITLE
Test serialization before parallel computation

### PR DESCRIPTION
**Pull request by sunqm**
Fix for https://github.com/pyscf/pyscf/issues/2232

### CODE REVIEW

**Comment by Haskiy** [comment]
It can not fix the bug that we discussed at wechat. However, the way you proposed "use threading executor only" can work with code modified below,
    if workers == 1:
        results = []
        for p0, p1 in _prange(0, ngrids, grids_per_task):
            r = _eval_xc_lebedev(func, rho_tm[...,p0:p1], deriv, spin_samples,
                                 collinear_threshold, collinear_samples)
            results.append(r)
    else:
            executor = ThreadPoolExecutor
            with executor(max_workers=workers) as ex:
                futures = []
                for p0, p1 in _prange(0, ngrids, grids_per_task):
                    f = ex.submit(_eval_xc_lebedev, func, rho_tm[...,p0:p1], deriv,
                                  spin_samples, collinear_threshold, collinear_samples)
                    futures.append(f)
                results = [f.result() for f in futures]

**Comment by sunqm** [comment]
I think changing to just `ThreadPoolExecutor` is acceptable. Could you please edit the PR directly? I think you have the permission to change the PR.

**Comment by Haskiy** [comment]
OK, I have finished that. How about the mcfun in PYPI? Shall we publish a new version?

**Comment by sunqm** [comment]
Yes, a new release is needed.

**Pull request merged**
